name: d3

networks:
  d3net:
    driver: bridge

services:
  frontend:
    build:
      context: "app"
    networks:
      - d3net
    ports:
      - "0.0.0.0:3000:3000"
    restart: unless-stopped

  backend:
    build:
      context: "backend"
    networks:
      - d3net
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
    restart: unless-stopped
